/*
Alex Kozak
February 26th 2018

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

#include "Solutions.h"
#include "stdafx.h"

int Problem2()
{
	int fibOld = 1;
	int fibNew = 1;
	int fibTotal = 1;

	int answer = 0;
	while (fibTotal < 4000000)
	{
		fibNew = fibTotal;
		fibTotal = fibOld + fibNew;
		fibOld = fibNew;
		if (fibTotal % 2 == 0)

		{
			answer += fibTotal;
		}
	}
	return answer;
}